ARG REDIS_VERSION=7.2.5
FROM bitnami/redis:${REDIS_VERSION}

COPY . /app
WORKDIR /app

# COPY start-redis-server.sh /usr/bin/start-redis-server.sh
# RUN chmod +x /usr/bin/start-redis-server.sh

# CMD ["/usr/bin/start-redis-server.sh"]
