name: build firecrawl image

on:
  push:
    branches:
      - main

jobs:

  call-docker-build:
    name: Call Docker Build
    uses: brigadecap/gha-workflows/.github/workflows/reusable-docker-build.yaml@main
    with:
      context: "{{defaultContext}}:apps"
      image-names: "ghcr.io/${{ github.repository }}"
    permissions:
      contents: read
      packages: write
      pull-requests: write
