name: build firecrawl image

on:
  push:
    branches:
      - main


jobs:
  call-docker-build:

    name: Call Docker Build

    uses: ./.github/workflows/docker-build.yaml
    

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: ./apps/api/Dockerfile
      image-names: |
        ghcr.io/${{ github.repository }}
